declare module 'lucide-react' {
    import { FC, SVGProps } from 'react';
    export interface IconProps extends SVGProps<SVGSVGElement> {
        size?: string | number;
        color?: string;
        strokeWidth?: string | number;
    }
    export type Icon = FC<IconProps>;
    export type LucideIcon = Icon;
    export const User: Icon;
    export const LogOut: Icon;
    export const LayoutDashboard: Icon;
    export const Briefcase: Icon;
    export const FileText: Icon;
    export const Bell: Icon;
    export const Settings: Icon;
    export const MapPin: Icon;
    export const GraduationCap: Icon;
    export const Languages: Icon;
    export const CheckCircle2: Icon;
    export const AlertCircle: Icon;
    export const TrendingUp: Icon;
    export const Calendar: Icon;
    export const Mail: Icon;
    export const Phone: Icon;
    export const ExternalLink: Icon;
    export const Info: Icon;
    export const Clock: Icon;
    export const Lightbulb: Icon;
    export const ShieldCheck: Icon;
    export const Award: Icon;
    export const ChevronDown: Icon;
    export const LayoutGrid: Icon;
    export const Search: Icon;
    export const BookOpen: Icon;
    export const Folder: Icon;
    export const ChevronRight: Icon;
    export const Eye: Icon;
    export const EyeOff: Icon;
    export const Camera: Icon;
    export const Lock: Icon;
    export const Clock: Icon;
    export const Building2: Icon;
    export const Plus: Icon;
    export const Trash2: Icon;;
    export const Upload: Icon;
    export const X: Icon;
    export const ChevronUp: Icon;
    export const Pencil: Icon;
    export const Quote: Icon;
    export const Check: Icon;
    export const ShieldAlert: Icon;
    export const Building: Icon;
    export const Globe: Icon;
    export const Users: Icon;
    export const ArrowLeft: Icon;
    export const Save: Icon;
}
